# Generated by Django 3.2.11 on 2022-06-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sid', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('img', models.ImageField(height_field=512, upload_to='', width_field=512)),
            ],
        ),
    ]
