# Generated by Django 3.2.11 on 2022-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollstudent',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
