# Generated by Django 3.2.11 on 2022-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_enrollstudent_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollstudent',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
